language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y mpg123
install:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov
  - npm install
script:
  - istanbul cover _mocha --report lcovonly -- --timeout 30000 -R spec test/**/*
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)