language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y mpg123
install:
  - npm install -g codecov
script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -R spec test/**/*
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)